// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: spider.proto

package spider_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type SpiderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsMobile bool `protobuf:"varint,1,opt,name=is_mobile,json=isMobile,proto3" json:"is_mobile,omitempty"`
}

func (x *SpiderReq) Reset() {
	*x = SpiderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpiderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpiderReq) ProtoMessage() {}

func (x *SpiderReq) ProtoReflect() protoreflect.Message {
	mi := &file_spider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpiderReq.ProtoReflect.Descriptor instead.
func (*SpiderReq) Descriptor() ([]byte, []int) {
	return file_spider_proto_rawDescGZIP(), []int{0}
}

func (x *SpiderReq) GetIsMobile() bool {
	if x != nil {
		return x.IsMobile
	}
	return false
}

// The response message containing the greetings
type SpiderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SpiderResp) Reset() {
	*x = SpiderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpiderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpiderResp) ProtoMessage() {}

func (x *SpiderResp) ProtoReflect() protoreflect.Message {
	mi := &file_spider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpiderResp.ProtoReflect.Descriptor instead.
func (*SpiderResp) Descriptor() ([]byte, []int) {
	return file_spider_proto_rawDescGZIP(), []int{1}
}

func (x *SpiderResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_spider_proto protoreflect.FileDescriptor

var file_spider_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x09, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x22,
	0x1e, 0x0a, 0x0a, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32,
	0x89, 0x01, 0x0a, 0x0d, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x4e, 0x42, 0x69, 0x6e, 0x67, 0x57, 0x61,
	0x6c, 0x6c, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3b,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x53, 0x42, 0x69, 0x6e, 0x67, 0x57, 0x61, 0x6c, 0x6c, 0x50,
	0x61, 0x70, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x69,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x70, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x73,
	0x70, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x62, 0x2f, 0x3b, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72,
	0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spider_proto_rawDescOnce sync.Once
	file_spider_proto_rawDescData = file_spider_proto_rawDesc
)

func file_spider_proto_rawDescGZIP() []byte {
	file_spider_proto_rawDescOnce.Do(func() {
		file_spider_proto_rawDescData = protoimpl.X.CompressGZIP(file_spider_proto_rawDescData)
	})
	return file_spider_proto_rawDescData
}

var file_spider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spider_proto_goTypes = []interface{}{
	(*SpiderReq)(nil),  // 0: proto.SpiderReq
	(*SpiderResp)(nil), // 1: proto.SpiderResp
}
var file_spider_proto_depIdxs = []int32{
	0, // 0: proto.SpiderService.GetCNBingWallPaper:input_type -> proto.SpiderReq
	0, // 1: proto.SpiderService.GetUSBingWallPaper:input_type -> proto.SpiderReq
	1, // 2: proto.SpiderService.GetCNBingWallPaper:output_type -> proto.SpiderResp
	1, // 3: proto.SpiderService.GetUSBingWallPaper:output_type -> proto.SpiderResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spider_proto_init() }
func file_spider_proto_init() {
	if File_spider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpiderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpiderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spider_proto_goTypes,
		DependencyIndexes: file_spider_proto_depIdxs,
		MessageInfos:      file_spider_proto_msgTypes,
	}.Build()
	File_spider_proto = out.File
	file_spider_proto_rawDesc = nil
	file_spider_proto_goTypes = nil
	file_spider_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SpiderServiceClient is the client API for SpiderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpiderServiceClient interface {
	// Sends a greeting
	GetCNBingWallPaper(ctx context.Context, in *SpiderReq, opts ...grpc.CallOption) (*SpiderResp, error)
	GetUSBingWallPaper(ctx context.Context, in *SpiderReq, opts ...grpc.CallOption) (*SpiderResp, error)
}

type spiderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiderServiceClient(cc grpc.ClientConnInterface) SpiderServiceClient {
	return &spiderServiceClient{cc}
}

func (c *spiderServiceClient) GetCNBingWallPaper(ctx context.Context, in *SpiderReq, opts ...grpc.CallOption) (*SpiderResp, error) {
	out := new(SpiderResp)
	err := c.cc.Invoke(ctx, "/proto.SpiderService/GetCNBingWallPaper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderServiceClient) GetUSBingWallPaper(ctx context.Context, in *SpiderReq, opts ...grpc.CallOption) (*SpiderResp, error) {
	out := new(SpiderResp)
	err := c.cc.Invoke(ctx, "/proto.SpiderService/GetUSBingWallPaper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiderServiceServer is the server API for SpiderService service.
type SpiderServiceServer interface {
	// Sends a greeting
	GetCNBingWallPaper(context.Context, *SpiderReq) (*SpiderResp, error)
	GetUSBingWallPaper(context.Context, *SpiderReq) (*SpiderResp, error)
}

// UnimplementedSpiderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSpiderServiceServer struct {
}

func (*UnimplementedSpiderServiceServer) GetCNBingWallPaper(context.Context, *SpiderReq) (*SpiderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCNBingWallPaper not implemented")
}
func (*UnimplementedSpiderServiceServer) GetUSBingWallPaper(context.Context, *SpiderReq) (*SpiderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUSBingWallPaper not implemented")
}

func RegisterSpiderServiceServer(s *grpc.Server, srv SpiderServiceServer) {
	s.RegisterService(&_SpiderService_serviceDesc, srv)
}

func _SpiderService_GetCNBingWallPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServiceServer).GetCNBingWallPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpiderService/GetCNBingWallPaper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServiceServer).GetCNBingWallPaper(ctx, req.(*SpiderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiderService_GetUSBingWallPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServiceServer).GetUSBingWallPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpiderService/GetUSBingWallPaper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServiceServer).GetUSBingWallPaper(ctx, req.(*SpiderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpiderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SpiderService",
	HandlerType: (*SpiderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCNBingWallPaper",
			Handler:    _SpiderService_GetCNBingWallPaper_Handler,
		},
		{
			MethodName: "GetUSBingWallPaper",
			Handler:    _SpiderService_GetUSBingWallPaper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spider.proto",
}
